############
version: 2.1
#############

commands:
  create_infra:
    steps:
      - run:
          name: "Create infra for test"
          command: |
            apk add curl

jobs:
  smoke_test:
    docker:
      # - image: python:3.7-alpine3.11
      # - image: circleci/redis
      # - image: ubuntu-2004:202008-01
      - image: alpine:latest
      #- image: cimg/base:2020.01
    steps:
      - checkout
      # - add_ssh_keys:
      #     fingerprints:
      #       - "84:a9:8b:d6:e9:68:1b:78:80:e0:4e:22:a3:0a:30:00"
      - create_infra
      - run:
          name: "Do a curl test"
          command: |
            # echo "Nooooooooooooooooooo: "; pwd
            # ansible-playbook ./.circleci/main-remote.yml -i inventory --private-key myKP6.pem
            if curl -s --head "https://google.com"
            then 
              echo "SUCCESS"
            else
              echo "FAILURE"
            fi
            
workflows:
  myworkflow:
    jobs:
      - smoke_test
        requires:
          - create_infra
